[metadata]
name = "<meta name="dicoding:email" content="yudhae@gmail.com">"

[theme]
primaryColor="#007AFF"
backgroundColor="#1C1C1E"
secondaryBackgroundColor="#2C2C2E"
textColor="#E5E5EA"
font="sans serif"